[Interface]
Address = 10.220.10.2/32
PrivateKey = <OPS_PRIVATE_KEY>
ListenPort = 51820

[Peer]
PublicKey = <DB_PUBLIC_KEY>
AllowedIPs = 10.220.10.10/32
Endpoint = <DB_PUBLIC_IP>:51820
PersistentKeepalive = 25
