#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE "${MIGRATION_DB_USER}" LOGIN PASSWORD '${MIGRATION_DB_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
  CREATE ROLE "${APP_DB_USER}" LOGIN PASSWORD '${APP_DB_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
  CREATE ROLE "${BI_DB_USER}" LOGIN PASSWORD '${BI_DB_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
  CREATE ROLE "${BACKUP_DB_USER}" LOGIN PASSWORD '${BACKUP_DB_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
  CREATE ROLE "${MONITOR_DB_USER}" LOGIN PASSWORD '${MONITOR_DB_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
  CREATE ROLE "${PGBOUNCER_AUTH_USER}" LOGIN PASSWORD '${PGBOUNCER_AUTH_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;

  ALTER DATABASE "${POSTGRES_DB}" OWNER TO "${MIGRATION_DB_USER}";
  ALTER SCHEMA public OWNER TO "${MIGRATION_DB_USER}";

  GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${MIGRATION_DB_USER}";
  GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${APP_DB_USER}", "${BI_DB_USER}", "${BACKUP_DB_USER}", "${MONITOR_DB_USER}", "${PGBOUNCER_AUTH_USER}";
  GRANT USAGE, CREATE ON SCHEMA public TO "${MIGRATION_DB_USER}";
  GRANT USAGE ON SCHEMA public TO "${APP_DB_USER}";
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${APP_DB_USER}";
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${APP_DB_USER}";
  ALTER DEFAULT PRIVILEGES FOR ROLE "${MIGRATION_DB_USER}" IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO "${APP_DB_USER}";
  ALTER DEFAULT PRIVILEGES FOR ROLE "${MIGRATION_DB_USER}" IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO "${APP_DB_USER}";
  GRANT pg_monitor TO "${MONITOR_DB_USER}";
  GRANT USAGE ON SCHEMA pgbouncer TO "${PGBOUNCER_AUTH_USER}";
  GRANT EXECUTE ON FUNCTION pgbouncer.get_auth(text) TO "${PGBOUNCER_AUTH_USER}";
EOSQL
